### ISSUE TITLE
flutter pub get issue 

### ISSUE THREAD

**Issue by sgruhier** [igniti0n/flutter_arhitect#4]
Hi 
Thanks for that cool idea!
I tried to run it locally but  I ran into that issue. 
Any idea how to fix it ?
```
[flutter_arhitect] flutter pub get
Resolving dependencies...
Because form_builder_validators <9.0.0-dev.1 depends on intl ^0.17.0 and every version of flutter_localizations from sdk depends on intl 0.18.0, form_builder_validators <9.0.0-dev.1 is incompatible with flutter_localizations from sdk.
So, because flutter_arhitect depends on form_builder_validators ^8.5.0 which depends on flutter_localizations from sdk, version solving failed.
exit code 1
```

**Comment by igniti0n** [comment]
Hi @sgruhier, thanks for reaching out about the issue!

This is due to the project using an older version of Flutter. Packages `form_builder_validators` and `flutter_form_builder` should be updated to the newest versions. The SDK should be updated to use the newer version as well `sdk: ">=3.0.0 <4.0.0"`.

I've updated the project to a higher version + the packages. Pull the latest changes, and let me know if you experience the issue.

**Comment by igniti0n** [comment]
Will close this issue - please open it if you have the issue still.
